export const ccs_buy_table_data = {
    head:['CVV',''],
    body:[
        {
            bin:'43433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'11220',
            database:'Apr#USA/WMIX_(ASEDEBILYA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'135433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'17620',
            database:'Apr#USA/WMIX_(afdfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'9.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'0896786',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'206534',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'12.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'45433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'18620',
            database:'Apr#USA/WMIX_(ASsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'18.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'094345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brolyn',
            state:'New York',
            zip:'72117620',
            database:'Apr#USA/WMIX_(AfdsfdssA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'80.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'367563',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'628560',
            database:'Apr#USA/WMIX_(GfdsfgfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'5.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'87655',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'76276570',
            database:'Apr#USA/WMIX_(WgfdgfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'22.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'odd'
        },
        {
            bin:'4345433',
            ccv:'CCV',
            yymm:'**/**',
            country:'UNITED STATES',
            bank:'CHASE BANK USA, N.A.',
            lavel:'CLASSIC',
            type:'DEBIT',
            holder:'Ja** ****',
            city:'Brooklyn',
            state:'New York',
            zip:'1877620',
            database:'Apr#USA/WMIX_(ASgfdsfdsA)_[Sniffed/HaveIP/LocalBase] (Daily Updates)',
            price:'8.00$',
            buy:'Buy',
            className:'even'
        },
    ]
}